name: Run Expectimax Bot
on:
  push:
    branches:
      - main
    paths:
      - 'expectimax.py'
jobs:
  expectimax:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Run Dumb bot
      run: python ./expectimax.py > expectimax.txt
      
    - name: Upload file to bucket
      uses: zdurham/s3-upload-github-action@master
      with:
       args: --acl public-read
      env:
        FILE: ./expectimax.txt
        AWS_REGION: 'eu-west-1'
        S3_BUCKET: '2048-ai-results'
        S3_KEY: 'expectimax.txt'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}