name: Run QLearning Bot
on:
  push:
    branches:
      - main
    paths:
      - 'qlearning.py'
jobs:
  MonteCarlo:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    
    - name: Run QLearning bot
      run: python ./qlearning.py > qlearning.txt
      
    - name: Upload file to bucket
      uses: zdurham/s3-upload-github-action@master
      with:
       args: --acl public-read
      env:
        FILE: ./qlearning.txt
        AWS_REGION: 'eu-west-1'
        S3_BUCKET: '2048-ai-results'
        S3_KEY: 'qlearning.txt'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}